import type { ControlledBone } from "@/types/avatar";

export const VRM_HUMANOID_BONE_CANDIDATES: Record<ControlledBone, string[]> = {
  head: ["head"],
  neck: ["neck"],
  chest: ["chest", "spine"],
  leftUpperArm: ["leftUpperArm"],
  leftLowerArm: ["leftLowerArm"],
  leftHand: ["leftHand"],
  leftThumbMetacarpal: ["leftThumbMetacarpal", "leftThumbProximal"],
  leftThumbProximal: ["leftThumbProximal"],
  leftThumbDistal: ["leftThumbDistal"],
  leftIndexProximal: ["leftIndexProximal"],
  leftIndexIntermediate: ["leftIndexIntermediate"],
  leftIndexDistal: ["leftIndexDistal"],
  leftMiddleProximal: ["leftMiddleProximal"],
  leftMiddleIntermediate: ["leftMiddleIntermediate"],
  leftMiddleDistal: ["leftMiddleDistal"],
  leftRingProximal: ["leftRingProximal"],
  leftRingIntermediate: ["leftRingIntermediate"],
  leftRingDistal: ["leftRingDistal"],
  leftLittleProximal: ["leftLittleProximal"],
  leftLittleIntermediate: ["leftLittleIntermediate"],
  leftLittleDistal: ["leftLittleDistal"],
  rightUpperArm: ["rightUpperArm"],
  rightLowerArm: ["rightLowerArm"],
  rightHand: ["rightHand"],
  rightThumbMetacarpal: ["rightThumbMetacarpal", "rightThumbProximal"],
  rightThumbProximal: ["rightThumbProximal"],
  rightThumbDistal: ["rightThumbDistal"],
  rightIndexProximal: ["rightIndexProximal"],
  rightIndexIntermediate: ["rightIndexIntermediate"],
  rightIndexDistal: ["rightIndexDistal"],
  rightMiddleProximal: ["rightMiddleProximal"],
  rightMiddleIntermediate: ["rightMiddleIntermediate"],
  rightMiddleDistal: ["rightMiddleDistal"],
  rightRingProximal: ["rightRingProximal"],
  rightRingIntermediate: ["rightRingIntermediate"],
  rightRingDistal: ["rightRingDistal"],
  rightLittleProximal: ["rightLittleProximal"],
  rightLittleIntermediate: ["rightLittleIntermediate"],
  rightLittleDistal: ["rightLittleDistal"],
};
